CREATE TABLE public.song_publication_consents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id bigint NOT NULL REFERENCES public.authors(id) ON DELETE CASCADE,
  song_id bigint NOT NULL REFERENCES public.songs(id) ON DELETE CASCADE,
  audio_rights_confirmed boolean NOT NULL CHECK (audio_rights_confirmed),
  cover_rights_confirmed boolean NOT NULL CHECK (cover_rights_confirmed),
  publishing_terms_accepted boolean NOT NULL CHECK (publishing_terms_accepted),
  policy_version text NOT NULL CHECK (length(btrim(policy_version)) > 0),
  accepted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT song_publication_consents_song_id_key UNIQUE (song_id)
);

CREATE INDEX song_publication_consents_author_id_idx
  ON public.song_publication_consents(author_id);

ALTER TABLE public.song_publication_consents ENABLE ROW LEVEL SECURITY;
