CREATE TABLE public.song_storage_cleanup_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket text NOT NULL CHECK (length(btrim(bucket)) > 0),
  object_paths jsonb NOT NULL CHECK (
    jsonb_typeof(object_paths) = 'array'
    AND jsonb_array_length(object_paths) > 0
  ),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error text,
  next_attempt_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX song_storage_cleanup_jobs_next_attempt_idx
  ON public.song_storage_cleanup_jobs(next_attempt_at, id);

ALTER TABLE public.song_storage_cleanup_jobs ENABLE ROW LEVEL SECURITY;
