create table public.authors (
  id bigint generated by default as identity,
  author text,
  "firstName" text,
  "lastName" text,
  email text not null,
  biograph text,
  author_image text,
  created_at timestamp with time zone not null default now(),
  password text not null,
  follows bigint default 0,
  constraint author_pkey primary key (id),
  constraint authors_author_key unique (author),
  constraint author_email_key unique (email)
);

create table public.playlists (
  id bigint generated by default as identity,
  name text,
  constraint playlist_pkey primary key (id)
);

create table public.types (
  id bigint generated by default as identity,
  type_name text not null,
  constraint types_pkey primary key (id),
  constraint types_type_name_key unique (type_name)
);

create table public.album (
  id bigint generated by default as identity,
  album_name text,
  created_at timestamp with time zone not null default now(),
  author_id bigint not null,
  constraint album_pkey primary key (id),
  constraint album_author_id_fkey foreign key (author_id)
    references public.authors (id) on update cascade on delete cascade
);

create table public.songs (
  id bigint generated by default as identity,
  "song_Name" text,
  file text,
  "song_Image" text not null,
  credit text,
  album_id bigint,
  created_at timestamp with time zone not null default now(),
  views bigint not null default 0,
  constraint songs_pkey primary key (id),
  constraint songs_album_id_fkey foreign key (album_id)
    references public.album (id) on update cascade on delete set null
);

create table public.authors_playlists (
  author_id bigint,
  playlist_id bigint,
  constraint authors_playlists_author_id_fkey foreign key (author_id)
    references public.authors (id) on update cascade on delete cascade,
  constraint authors_playlists_playlist_id_fkey foreign key (playlist_id)
    references public.playlists (id) on update cascade on delete cascade
);

create table public.playlists_songs (
  playlist_id bigint,
  song_id bigint,
  constraint playlists_songs_playlist_id_fkey foreign key (playlist_id)
    references public.playlists (id) on update cascade on delete cascade,
  constraint playlists_songs_song_id_fkey foreign key (song_id)
    references public.songs (id) on update cascade on delete cascade
);

create table public.songs_types (
  song_id bigint,
  type_id bigint,
  constraint songs_types_song_id_fkey foreign key (song_id)
    references public.songs (id) on update cascade on delete cascade,
  constraint songs_types_type_id_fkey foreign key (type_id)
    references public.types (id) on update cascade on delete cascade
);

create table public.authors_songs (
  author_id bigint,
  song_id bigint,
  constraint authors_songs_author_id_fkey foreign key (author_id)
    references public.authors (id) on update cascade on delete cascade,
  constraint authors_songs_song_id_fkey foreign key (song_id)
    references public.songs (id) on update cascade on delete cascade
);

create table public.views (
  id bigint generated by default as identity,
  user_id bigint,
  song_id bigint,
  created_at timestamp with time zone not null default now(),
  constraint views_pkey primary key (id),
  constraint views_user_id_fkey foreign key (user_id)
    references public.authors (id) on update cascade on delete set default,
  constraint views_song_id_fkey foreign key (song_id)
    references public.songs (id) on update cascade on delete set default
);

comment on table public.views is 'keeps a views of song(song_id), user(user_id) so who was listening to. the table keeps date when the user was listening to the song. the table will be use for monthly_song_stats.';

create table public.monthly_song_stats (
  id bigint generated by default as identity,
  year text,
  month text,
  views bigint,
  song_id bigint,
  created_at timestamp with time zone not null default now(),
  rank bigint,
  constraint monthly_song_stats_pkey primary key (id),
  constraint monthly_song_stats_song_id_fkey foreign key (song_id)
    references public.songs (id) on update cascade on delete set default
);

comment on table public.monthly_song_stats is 'it contains id, year and month of when the stats was made, views the song reached in the particular year/month, song_id,  when the stats was created.';

create table public.song_publication_consents (
  id bigint generated by default as identity,
  author_id bigint not null,
  song_id bigint not null,
  audio_rights_confirmed boolean not null,
  cover_rights_confirmed boolean not null,
  publishing_terms_accepted boolean not null,
  policy_version text not null,
  accepted_at timestamp with time zone not null default now(),
  constraint song_publication_consents_pkey primary key (id),
  constraint song_publication_consents_author_id_fkey foreign key (author_id)
    references public.authors (id) on delete cascade,
  constraint song_publication_consents_song_id_fkey foreign key (song_id)
    references public.songs (id) on delete cascade,
  constraint song_publication_consents_song_id_key unique (song_id),
  constraint song_publication_consents_audio_rights_confirmed_check check (audio_rights_confirmed),
  constraint song_publication_consents_cover_rights_confirmed_check check (cover_rights_confirmed),
  constraint song_publication_consents_publishing_terms_accepted_check check (publishing_terms_accepted),
  constraint song_publication_consents_policy_version_check check (length(btrim(policy_version)) > 0)
);

create index song_publication_consents_author_id_idx
  on public.song_publication_consents (author_id);

create table public.song_storage_cleanup_jobs (
  id bigint generated by default as identity,
  bucket text not null,
  object_paths jsonb not null,
  attempts integer not null default 0,
  last_error text,
  next_attempt_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  constraint song_storage_cleanup_jobs_pkey primary key (id),
  constraint song_storage_cleanup_jobs_bucket_check check (length(btrim(bucket)) > 0),
  constraint song_storage_cleanup_jobs_object_paths_check check (
    jsonb_typeof(object_paths) = 'array' and jsonb_array_length(object_paths) > 0
  ),
  constraint song_storage_cleanup_jobs_attempts_check check (attempts >= 0)
);

create index song_storage_cleanup_jobs_next_attempt_idx
  on public.song_storage_cleanup_jobs (next_attempt_at, id);

alter table public.authors enable row level security;
alter table public.playlists enable row level security;
alter table public.types enable row level security;
alter table public.album enable row level security;
alter table public.songs enable row level security;
alter table public.authors_playlists enable row level security;
alter table public.playlists_songs enable row level security;
alter table public.songs_types enable row level security;
alter table public.authors_songs enable row level security;
alter table public.views enable row level security;
alter table public.monthly_song_stats enable row level security;
alter table public.song_publication_consents enable row level security;
alter table public.song_storage_cleanup_jobs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'spotify',
  'spotify',
  true,
  26214400,
  array['audio/mpeg', 'image/jpeg', 'image/png']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
